### PR TITLE
Setting SWIFT_INSTALL_OBJ_HEADER to YES

### PR DESCRIPTION
**Pull request by maercam**
Setting SWIFT_INSTALL_OBJ_HEADER to YES helps carthage update use flag cache-build and project doesn’t rebuild after each update

If SWIFT_INSTALL_OBJ_HEADER doesn't set to YES build process doesn't generate EmitterKit-Swift.h.
If EmitterKit-Swift.h doesn't generate carthage cannot check swift's version parsed from that file so build cache is invalid and each time project is rebuilding

### CODE REVIEW

**Comment by aleclarson** [comment]
@maercam Good work, thanks for the help! Clearly, I don't use Carthage. 😛

**Comment by aleclarson** [comment]
@maercam Do you think #41 should be merged?

**Comment by maercam** [comment]
I don't yet. I can look at it later. Could you make release with my last changes?

**Comment by aleclarson** [comment]
@maercam Yes I will, but I'd like to merge that PR along with it, if possible. I also have two other commits in progress that will be included in the next release. Coming up shortly.

**Comment by aleclarson** [comment]
v5.2.0 has been released 🎉

**Pull request merged**
