### PR TITLE
Carthage compatibility for macOS, tvOS & watchOS

### PR DESCRIPTION
**Pull request by simonrice**
This project as-is seems to be Carthage compatible for iOS. This PR adds schemes & compatibility for macOS, tvOS & watchOS.

### CODE REVIEW

**Comment by aleclarson** [comment]
Why can't Carthage use the same scheme for each platform? Is there some documentation you can point me to?

**Comment by simonrice** [comment]
Thank you for looking at this.

In fact it is possible to improve this by just having one scheme - it will need to be modified & [you can find out more about the changes I'm making here](http://promisekit.org/news/2016/08/Multiplatform-Single-Scheme-Xcode-Projects/).  I'll be more than happy to do the honours & I'll let you know if I find any stumbling blocks.

**Comment by simonrice** [comment]
Feel free to give this all another review.  The tests don't run in macOS (due to no UIKit for `ChangeListenerTests`) or watchOS (due to no XCTest), but the tests run in both tvOS & iOS.

**Comment by yonaskolb** [comment]
@aleclarson is this possible to get merged and into a new release? We'd like to use EmitterKit with Carthage in a tvOS app

**Comment by aleclarson** [comment]
We can merge this once #43 gets fixed. Are any updates necessary?

**Pull request merged**
