### PR TITLE
fixing nil listening issue with Notifier

### PR DESCRIPTION
**Pull request by markshiz**

### CODE REVIEW

**Comment by aleclarson** [comment]
Nice catch! Any ideas on how we can support listening to notifs where `notif.object` **must** be nil (the current behavior)? It's an edge case, but maybe there's a way to keep that functionality without introducing a breaking change?

We could add a boolean property that allows your suggested functionality (listening to all notifs when the target is nil).

```swift
listener = event.on { (userInfo: NSDictionary) in
  // Since `strict` is false, the value of `notif.object` is not checked.
}
listener.strict = false
```

Or we could just offload that responsibility by passing `notif.object` as the second param to the listener.

```swift
listener = event.on { (userInfo: NSDictionary, object: Any?) in
  if (object == nil) {
    // This achieves the original functionality.
  }
}
```

I'm leaning towards the second one, since it's cleaner. It's a breaking change for anyone listening to a notif where `notif.object` might be nil or non-nil, but that's probably a rare scenario.

**Comment by markshiz** [comment]
Yes, I like the latter suggestion.  One other possibility would be to send a `NSNotification` object in the callback.  Both the `object` and `NSDictionary` are available from that object.

**Comment by aleclarson** [comment]
Good point, I'll make that change in another commit.

Before I merge this PR, you'll need to fix one thing.

When the `NotificationListener` has a "target" and `notif.object` is nil, the listener should not be triggered.

Here's the updated code:

```swift
if self._targetID != "0" {
  if let target: AnyObject = notif.object as AnyObject? {
    if self._targetID != getHash(target) {
      return
    }
  } else {
    return
  }
}
```

**Comment by markshiz** [comment]
LGTM

**Comment by aleclarson** [comment]
Merged into [v5.1.0](https://github.com/aleclarson/emitter-kit/tree/5.1.0) 🎉 

Thanks for your contribution!

**Pull request closed without merging**
